#!/usr/bin/env bash

for i in 0.0.1 0.0.2 0.0.4 1.0.1 1.0.2 1.0.3 1.0.4 1.0.5 1.0.6 1.0.7 1.0.8 1.0.9 1.0.10; do
  if [ ! -d $i ]; then
    mkdir $i

    cp 1.0.2/* ${i}/
    sed -i "s/1\\.0\\.2/${i}/" ${i}/Dockerfile
  fi

done
